feat: Implement a way to stop a heartbeat.
WalletConnect/walletconnect-utils pull request #46
Opened 2022-12-21 14:21 UTC by antondalgren

The interval is holding up the process from exiting during testing. This fix is probably one part of fixing the issue [#1507](https://github.com/WalletConnect/walletconnect-monorepo/issues/1507)

We found that this interval was lingering in tests using the package `wtfnode`.

2022-12-21 14:22 UTC, antondalgren commented
@ganchoradkov

2022-12-23 10:26 UTC, antondalgren commented
@bkrem

2023-01-04 10:26 UTC, antondalgren commented
ping @bkrem @ganchoradkov @pedrouid

2023-01-12 10:29 UTC, ganchoradkov requested changes

2023-01-12 10:29 UTC, ganchoradkov commented on misc/heartbeat/src/heartbeat.ts
> +    this.intervalRef = setInterval(() => this.pulse(), toMiliseconds(this.interval));
I'm getting this error `Type 'Timeout' is not assignable to type 'number'.ts(2322)`.
Seems to require `private intervalRef?: NodeJS.Timeout`

2023-01-16 08:17 UTC, antondalgren commented on misc/heartbeat/src/heartbeat.ts
> +    this.intervalRef = setInterval(() => this.pulse(), toMiliseconds(this.interval));
Sorry, the return type seems to differ based on runtime (browser/node). [8d54911](https://github.com/WalletConnect/walletconnect-utils/pull/46/commits/8d549117543493f7350a4b88ff58ca0ddac0f170) should fix this.

2023-01-16 10:20 UTC, ganchoradkov approved these changes
LGTM, thanks for contributing :100:

2023-01-16 10:20 UTC, merged